global:
  resolve_timeout: 1m
  slack_api_url: https://hooks.slack.com/services/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

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#observability'
        send_resolved: false