global:
  resolve_timeout: 1m
  slack_api_url: ${SLACK_API_WEBHOOK_URL}

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#observability'
        send_resolved: true