global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager:9093

rule_files:
  - "rules-for-alert-manager.yml"

scrape_configs:
  - job_name: 'UserAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'app:8080' ]
        labels:
          application: 'User API'
  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
        labels:
          application: 'Postgres DB'